<?php


namespace Toolbox\Core\Component;


class IBlockComponent extends BaseComponent implements IBlockComponentInterface
{
    public function onPrepareComponentParams($arParams)
    {
        $this->isIBlock($arParams);
        return parent::onPrepareComponentParams($arParams); // TODO: Change the autogenerated stub
    }


    public function isIBlock($arParams)
    {
        if (empty($arParams['IBLOCK_ID'])){
            throw new \Exception('Not set IBLOCK_ID.');
        }
    }

}